# ESP32Home Configuration YAML
# This is the configuration file for the ESP32Home firmware
# For use with the attached pcb design

esphome:
  name: master-bme680
  friendly_name: Master-BME680

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

mqtt:
  broker: 192.168.1.15
  topic_prefix: esphome/master

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret home_assistant_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: master.domum.net
  domain: ".domum.net"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Master-Bme680 Fallback Hotspot"
    password: "m4g7SX7NsGIX"

  manual_ip:
    static_ip: 192.168.1.178
    gateway: 192.168.1.1
    subnet: 255.255.255.0

i2c:
  sda: "GPIO9"
  scl: "GPIO8"
  scan: True

sensor:
  - platform: bme680
    temperature:
      name: "BME680 Temperature"
      oversampling: 16x
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    gas_resistance:
      name: "BME680 Gas Resistance"
    address: 0x77
    update_interval: 60s
